// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LunchUp.Model.Migrations
{
    [DbContext(typeof(LunchUpContext))]
    internal class LunchUpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("LunchUp.Model.Models.PersonEntity", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("varchar(36)");

                b.Property<string>("Company")
                    .HasColumnType("text");

                b.Property<string>("Email")
                    .HasColumnType("text");

                b.Property<string>("Firstname")
                    .HasColumnType("text");

                b.Property<string>("Lastname")
                    .HasColumnType("text");

                b.Property<DateTime?>("OptIn")
                    .HasColumnType("timestamp without time zone");

                b.Property<string>("Photo")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Person");
            });

            modelBuilder.Entity("LunchUp.Model.Models.ResponseEntity", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("varchar(36)");

                b.Property<bool>("Like")
                    .HasColumnType("boolean");

                b.Property<string>("OriginId")
                    .HasColumnType("varchar(36)");

                b.Property<DateTime>("ResponseDate")
                    .HasColumnType("timestamp without time zone");

                b.Property<string>("TargetId")
                    .HasColumnType("varchar(36)");

                b.HasKey("Id");

                b.HasIndex("OriginId");

                b.HasIndex("TargetId");

                b.ToTable("Response");
            });

            modelBuilder.Entity("LunchUp.Model.Models.ResponseEntity", b =>
            {
                b.HasOne("LunchUp.Model.Models.PersonEntity", "Origin")
                    .WithMany()
                    .HasForeignKey("OriginId");

                b.HasOne("LunchUp.Model.Models.PersonEntity", "Target")
                    .WithMany()
                    .HasForeignKey("TargetId");
            });
#pragma warning restore 612, 618
        }
    }
}